import type { Metadata } from "next";
import { Stack_Sans_Headline, Noto_Sans } from "next/font/google";
import "./globals.css";

//Heading Font 
const headingFont = Stack_Sans_Headline({
  variable: "--font-stack-notch",
  subsets: ["latin"],
});

//Body Font
const bodyFont = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${bodyFont.variable} h-full antialiased`}
    >
      <body className={"${bodyFont.className} min-h-full flex flex-col"}
      >
        {children}
      </body>
    </html>
  );
}
